### ISSUE TITLE
Try to get rid of three.js dependency

### ISSUE THREAD

**Issue by bjorn-einar-bjartnes-4ss** [bjartwolf/shaderfish#10]
Should be possible to get rid of three.js and just compile the shader...
should be possible to get the webgl context and compile shaders and stuff with no deps
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#contexttype

**Comment by bjartwolf** [comment]
adressed in https://github.com/bjartwolf/shaderfish/commit/7d2a5829f650bff0f7be6d4265d45429a05dfa55
